// NeuroStack omp adapter — generated by `neurostack hooks install --harness omp`.
// It maps omp events onto `neurostack hook <event>` and applies the verdict: exit 2
// blocks the call and stdout is the reason, stdout otherwise gets injected. Every
// retrieval and suppression decision belongs to the CLI, never to this file.
//
// Checkpoints say nothing to the session model. The adapter sends one frozen
// message window to `hook checkpoint --run`; Python persists it before running
// `checkpoint_command`, then saves outside the chat. `/save` starts the same
// path and displays one brief status line.
type Block = { type?: string; text?: string };
type Content = string | Block[] | undefined;
type Msg = { role?: string; content?: Content };
type Ctx = {
  sessionManager?: { getSessionId?: () => string };
  setInterval?: (fn: () => void, ms: number) => unknown;
};
type Ev = Msg & { toolName?: string; input?: unknown; isError?: boolean; messages?: Msg[] };
type Pi = {
  on: (e: string, h: (ev: Ev, ctx: Ctx) => unknown) => void;
  sendMessage: (m: object) => void;
  registerCommand: (name: string, c: { description: string; handler: () => unknown }) => void;
};

const BIN = "__NEUROSTACK_BIN__";
const FALLBACK_SESSION = `omp-${Date.now().toString(36)}-${process.pid}`;
let session = FALLBACK_SESSION;
// Checkpoint cadence: 40 new messages, or 30 quiet minutes with at least 5.
const EVERY_MESSAGES = 40;
const QUIET_MS = 30 * 60_000;
const MIN_MESSAGES = 5;
const TICK_MS = 60_000;

function spawn(args: string[], stdin: string) {
  const proc = Bun.spawn([BIN, "hook", ...args], { stdin: "pipe", stdout: "pipe", stderr: "ignore" });
  proc.stdin.write(stdin);
  proc.stdin.end();
  return proc;
}
function event(name: string, payload: Record<string, unknown>, args: string[] = []) {
  return spawn([name, ...args], JSON.stringify({ session, harness: "omp", workspace: process.cwd(), ...payload }));
}
async function hook(name: string, payload: Record<string, unknown>) {
  const proc = event(name, payload);
  const text = (await new Response(proc.stdout).text()).trim();
  return { text, code: await proc.exited };
}
const textOf = (c: Content): string =>
  typeof c === "string" ? c : (c ?? []).filter((b) => b.type === "text").map((b) => b.text ?? "").join("\n");
const append = (c: Content, note: string): Content =>
  typeof c === "string" ? c + note : [...(c ?? []), { type: "text", text: note }];

async function cursor(): Promise<number> {
  const { text } = await hook("checkpoint-cursor", {});
  try {
    const value = JSON.parse(text).since_index;
    return typeof value === "number" && value >= 0 ? value : 0;
  } catch {
    return 0;
  }
}

export default function neurostack(pi: Pi): void {
  let seen: Msg[] = [];
  let settled = 0;
  let offered = 0;
  let lastMessageAt = Date.now();

  async function checkpoint(): Promise<{ pending: number; busy: boolean }> {
    const pending = seen.length - settled;
    if (pending < MIN_MESSAGES) return { pending, busy: false };
    if (offered > settled) return { pending, busy: true };
    offered = seen.length;
    const submittedStart = settled;
    const submittedEnd = offered;
    const proc = event("checkpoint", { since_index: submittedStart,
      messages: seen.slice(submittedStart, submittedEnd) },
      ["--run", "--harness", "omp", "--session", session]);
    void new Response(proc.stdout).text().then(async () => {
      settled = Math.max(settled, await cursor());
    }).finally(() => {
      offered = settled;
    });
    proc.unref();
    return { pending, busy: false };
  }

  pi.on("session_start", async (_e, ctx) => {
    session = ctx?.sessionManager?.getSessionId?.() || FALLBACK_SESSION;
    settled = await cursor();
    offered = settled;
    const { text } = await hook("session-start", {});
    if (text) pi.sendMessage({ customType: "neurostack-brief", content: text, display: true });
    ctx?.setInterval?.(() => {
      if (Date.now() - lastMessageAt >= QUIET_MS) void checkpoint();
    }, TICK_MS);
  });
  pi.registerCommand("save", {
    description: "Checkpoint this session into NeuroStack memory",
    handler: async () => {
      const result = await checkpoint();
      pi.sendMessage({
        customType: "neurostack-save",
        content: result.pending < MIN_MESSAGES
          ? `NeuroStack: nothing to save yet (${result.pending} messages)`
          : result.busy ? "NeuroStack: checkpoint already running"
          : "NeuroStack: checkpoint started in the background",
        display: true,
      });
    },
  });
  pi.on("tool_call", async (e) => {
    const { text, code } = await hook("tool-call", { tool: e.toolName, input: e.input });
    if (code === 2 && text) return { block: true, reason: text };
  });
  pi.on("tool_result", async (e) => {
    if (e.isError !== true) return;
    const { text } = await hook("tool-result", { tool: e.toolName, error: textOf(e.content) });
    if (text) return { content: append(e.content, `\n\n${text}`) };
  });
  pi.on("context", async (e) => {
    const messages = e.messages ?? [];
    seen = messages;
    lastMessageAt = Date.now();
    if (messages.length - settled >= EVERY_MESSAGES) void checkpoint();
    const i = messages.map((m) => m.role).lastIndexOf("user");
    if (i < 0) return;
    const { text } = await hook("prompt", { prompt: textOf(messages[i].content) });
    if (!text) return;
    const next = messages.slice();
    next[i] = { ...messages[i], content: append(messages[i].content, `\n\n${text}`) };
    return { messages: next };
  });
  // Harvest outlives the session: hand the transcript id over and detach.
  pi.on("session_shutdown", (_e, ctx) => {
    event("session-end", { session: ctx?.sessionManager?.getSessionId?.() ?? session, format: "omp" }).unref();
  });
}
